const CulturalData = [
    {
        id: 2,
        name: "NrutyamS",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Nrutyam(Solo)",
        headingPara: "Get ready to experience the vibrant and colorful world of Indian culture with our Inter College Solo Dance Competition! This year's fest is themed around the rich traditions ofIndia, and we invite dancers from all backgrounds to showcase their skills in acelebration of this fascinating culture. From classical Indian dance styles likeBharatanatyam and Kathak, to Bollywood-inspired routines that fuse traditional moveswith modern flair, our Solo Dance Competition offers a platform for dancers to expressthemselves creatively while honoring the beauty and diversity of Indian culture. (Day 1 : 11Am - 12Pm)",
        rules: [
            "1. The duration of the performance should not exceed 3 minutes.",
            "2. The participant can perform one song or a medley of songs with an Indian cultural theme.",
            "3. The event heads should be made aware of the props being used (if any) by the performer in advance.",
            "4. A section of at least 1 minute relevant to the fest theme (Indian Culture) should be included in the performance.",
            "5. Contestants have to report 30 minutes prior to event time.",
            "6. All the participants will receive a participation certificate.",
            "7. The decision of the judges will be final and abiding to all.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/NrutyamS",
    },
    {
        id: 3,
        name: "NrutyamG",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Nrutyam(Group)",
        headingPara: "Get ready to witness a spectacle of rhythmic movements and dazzling colors at the InterCollege Group Dance competition with a theme of Indian Culture! This high-energy eventbrings together talented teams of dancers who will take you on a journey through themesmerizing traditions of India. The beats of traditional Indian music will get your feettapping, while the vibrant costumes and intricate choreography will leave youspellbound. You'll see a fusion of classical and contemporary dance styles that reflectthe rich cultural heritage of India. From the graceful movements of Kathak to theenergetic Bhangra, each performance is a testament to the creativity and passion of thedancers. With each beat of the music, the dancers bring to life the stories and legends ofIndia, showcasing the diversity and beauty of this ancient land. As you watch thesetalented performers, you'll feel yourself getting swept away by the magic of Indian danceand culture. So come, immerse yourself in the colors, music, and traditions of India at theGroup Dance competition, and let the magic unfold before your eyes! (Day 1 : 9:30Am-10:30Am)",
        rules: [
            "1. The duration of the performance should not exceed 8 minutes.",
            "2. The team can perform one song or a medley of songs with Indian cultural theme touch that the group performers take up for the dance performance.",
            "3. The event heads should be made aware of the props being used (if any) by the performer in advance.",
            "4. A section of at least 2 minutes relevant to the fest theme (Indian Culture) should be included in the performance.",
            "5. Contestants have to report 45 minutes prior to event time.",
            "6. All the participants will receive a participation certificate.",
            "7. The decision of the judges will be final and abiding to all.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/NrutyamG",
    },
    {
        id: 4,
        name: "SurLayTaalS",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Sur Lay Taal (Solo)",
        headingPara: "Get ready to be transported to the vibrant and colorful world of Indian culture, where music reigns supreme! The Inter College Solo Singing Competition with an Indian Culture theme promises to be a feast for the senses, with contestants showcasing their vocal prowess and bringing to life the rich musical heritage of India. From soulful ghazals to upbeat bhangra, this competition is sure to leave you captivated and entranced. So sit back, relax, and let the power of Indian music wash over you in this unforgettable celebration of talent and culture(Day 1: 1:30Pm-2:30Pm)",
        rules: [
            "1. Participant must bring their karaoke (Pen drive).",
            "2. Cuss actions/words will not be entertained and thus will lead to disqualifications.",
            "3. Contestants have to report 30 minutes before the event.",
            "4. The duration of the performance should not exceed 4 minutes. Exceeding will lead to a reduction in the final score.",
            "5. Each contestant will be provided only a mic/mic stand and karaoke beats, if they want to use any other instruments, they must bring themselves.",
            "6. Judge’s decision will be final and abiding.",
            "7. Winners will be awarded and all the participants will be awarded participation certificates.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/SurLayTaalS",
    },
    {
        id: 5,
        name: "SurLayTaalG",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Sur Lay Taal (Group)",
        headingPara: "Get ready to witness the power of harmony and the beauty of Indian culture in the Group Singing Competition! With a theme that celebrates the rich musical heritage of India, our talented groups will showcase their vocal talents and take you on a mesmerizing journey through the diverse sounds and rhythms of Indian music.From classical ragas to peppy Bollywood numbers, this competition promises to leave you spellbound and thoroughly entertained.So gather your friends and family, and get ready to be transported to a world of music, culture, and pure joy in this unforgettable celebration of group singing and Indian culture. (Day 1: 12:00Pm - 1:30Pm)",
        rules: [
            "1. Participant must bring their karaoke (Pen drive).",
            "2. Cuss actions/words will not be entertained and thus will lead to disqualifications.",
            "3. Contestants have to report 30 minutes before the event.",
            "4. The duration of the performance should not exceed 7 minutes. Exceeding will lead to a reduction in the final score.",
            "5. Each contestant will be provided only a mic/mic stand and karaoke beats, if they want to use any other instruments, they must bring themselves.",
            "6. Judge’s decision will be final and abiding.",
            "7. Winners will be awarded and all the participants will be awarded participation,certificates."

        ],

        paymentLink: "",
        redirectLink: "/cultural/SurLayTaalG",
    },
    {
        id: 6,
        name: "vyang",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Vyang",
        headingPara: "Get ready for a theatrical extravaganza as the Inter-College Nukkad Natak Competition takes center stage! This competition brings together the best and brightest college students to showcase their creativity, talent, and social awareness through the art of street theater. With thought-provoking themes and hard-hitting messages, these nukkad nataks promise to leave you entertained, inspired, and motivated to make a difference in the world. So gather your friends, bring your energy, and get ready to witness the power of theater in this unforgettable celebration of creativity and social change (Day 1: 10:00Am-1:00Pm)",
        rules: [
            "1. A team can consist of a maximum of 25 participants. This represents the number of people registered as a team. Only registered participants shall be allowed to perform the street play.",
            "2. All the registered participants in a team should be current students of the same college. Only one team per college is allowed to participate.",
            "3. The time limit of performance is a maximum of 20 minutes including setup. A warning bell will ring after 18 minutes. Anything beyond 20 minutes limit will not be counted and negative marks will be awarded for overtime.",
            "4. Music accompanists are included in the team number stated above. Music is allowed to be played only inside the circle of performance.",
            "5. On ly live music is allowed. Teams will have to bring their instruments. Obscenity (at the discretion of the judges) of any kind is not allowed and will lead to immediate disqualification.",
            "6. No electrical appliances shall be allowed during the performance, whether inside or outside the circle of performance.",
            "7. Teams are expected to perform at an open-air venue, on a circular stage with an audience on all sides. Use of fire/water/smoke machines on stage/near the stage is not permitted.",
            "8. The language of performance must be Hindi/English, regional languages could be used for a maximum of 15-20% of the performance."
        ],

        paymentLink: "",
        redirectLink: "/cultural/vyang",
    },
    {
        id: 7,
        name: "Jalsa",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Jalsa",
        headingPara: "Are you ready to be swept away in a whirlwind of style and culture? Then get ready to witness the most spectacular event of the year - the Inter College Fashion Show, Indian Edition! Get lost in the vibrant hues and mesmerizing patterns of India's rich fashion heritage as the most talented young souls showcase their awe-inspiring creations on the runway. From the intricate embroidery of the lehengas to the graceful drapes of the sarees, every garment tells a unique story of India's history and traditions. Join us for an unforgettable event of glitz, glamour, sheer brilliance, and professional photoshoot as the contestants battle it out for the coveted title. Be amazed by the ingenuity and creativity of the designs, and experience the electric atmosphere as the models sashay down the runway. Don't miss out on this once-in-a-lifetime opportunity to witness the magic of Indian fashio (Day 2: 1:00Pm-4:00Pm)",
        rules: [
            "1. Entry should be in teams. No single participation is allowed.",
            "2. Only one team per college is allowed to participate.",
            "3. The event comprises two rounds:",
            "Round 1: #daretobedifferent",
            "4. The time limit for each team would be 8-10 minutes each (Including setup and performance).",
            "Round 2 – #speakyourmind",
            "5. After shortlisting of best 3 teams for the first round, one representative from each team will be called onto the stage to answer questions asked by the judge.",
            "6. The theme for the fashion show is “INDIA'S HIDDEN HUES (INDIA'S CULTURE)”.",
            "7. Each participant will receive a registration number/ code after their registration along with one POC. A green room would be provided for the changing purpose.",
            "8. Delay in the arrival to the stage upon announcing the name or code must be strictly avoided. The announcement will be done a maximum of twice, failing to arrive will be disqualified.",


            "9. Judge’s decision shall be final and abiding.",
            "10. Participants will be judged on costumes, theme, walking stance, attitude, and tagline.",
            "11. Irrelevant bare - body exposure is prohibited and importance will be given to the appropriate use of costumes and accessories.",
            "12. All costumes are permitted, which maintain decency including original costumes & fashion designs.",
            "13. All the participants will receive a participation certificate.",
            "14. Submit the music of your competitive performances to the stage committee at the registration counter immediately after arriving on the college premises.Pen drives are allowed."

        ],

        paymentLink: "",
        redirectLink: "/cultural/Jalsa",
    },
    {
        id: 8,
        name: "Swaang",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Swaang",
        headingPara: "Are you ready for an event of laughter, drama, and entertainment? Then gear up for the Inter College Skit competition! This year's theme celebrates the diversity and richness of Indian culture, with hilarious and heartwarming skits that will leave you in stitches. From traditional tales to modern-day scenarios, witness the talent and creativity of the country's best young performers as they take the stage and bring their stories to life. Be mesmerized by the colorful costumes, the dynamic performances, and the catchy music as the contestants battle it out for the title of the best skit. Immerse yourself in the magic of India's culture, and let the humor and emotion of the skits sweep you away. So come and be a part of the action at the Inter College Skit competition! Get ready for an unforgettable night of entertainment and laughter, and witness firsthand the incredible talent and passion of India's budding performers. (Day 2: 9:30Am - 12:30Pm) ",
        rules: [
            "1. Only registered participants shall be allowed to perform the act.All the registered participants in a team should be current students of the same college.Only one team per college is allowed to participate.",
            "2. The time limit of performance is a maximum of 20 minutes(including setup).A warning bell will ring after 18 minutes.Anything beyond 20 minutes limit will not be counted and negative marks will be awarded for overtime.",
            "   3.    Music / Audio / Background Video effects are allowed but the soft copies should be provided beforehand and a member of the acting group should be present to control Sounds and lights.",
            "4. All props/ sets / costumes are to be brought by the performing team only.Nothing in this regard will be provided by the organizing committee.",
            "5. Teams should reach at least 60 minutes prior to the starting time of the event for the purpose of registration and rehearsal with light and sound.Every member should bring their college ID cards along with them.",
            "6. The decision of the judges will be final.The organizing committee holds the right to disqualify a candidate in case the rules are not followed.",
            "7. Violence of any kind will lead to immediate disqualification of the team.",


            "8. The use of fire / intoxicants / or anything that could harm college property is strictly prohibited within the premise of ABES Engineering College.",
            "9. Obscenity, foul language, and acts offensive to any genre of people are strictly prohibited.",
            "10. All the participants will receive a participant certificate",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Swaang",
    },
    {
        id: 9,
        name: "Tarana",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Tarana",
        headingPara: "Ladies and Gentlemen, get ready to witness the ultimate fusion of talent and culture as we present to you the Inter College Instrumental competition based on Indian Culture Theme! The stage is set for an electrifying event that will showcase the best musicians from colleges all across the city, each vying for the top spot with their unique blend of classical and contemporary Indian music. With a dazzling array of instruments, ranging from the haunting melodies of the sitar to the thunderous beats of the tabla, this competition promises to be a truly unforgettable experience. So come join us, as we embark on a journey through the rich and vibrant tapestry of Indian music and witness the birth of a new generation of musical maestros!",
        rules: [
            "1. The performance should not last more than 10 minutes.",
            "2. The player must play his or her instrument by the theme provided by the team.",
            "3. The judges' decision will be final and abiding to all.",
            "4. Participants are allowed 2 minutes for preparation.",
            "5. Only 1 team from each college is allowed.",
            "6. The event will consist of a single round of performances.",
            "7. All the participants will receive a participation certificate",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Tarana",
    },
    {
        id: 10,
        name: "Decibels",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Decibels",
        headingPara: "Get ready to rock and roll as the Inter College Battle of Bands takes the stage! This year's competition promises to be the ultimate showdown of musical talent, with bands from across the colleges competing for the coveted title. Be prepared to witness the electrifying energy of the performances, as the contestants belt out their best tunes and show off their musical prowess. From classic rock to indie pop, there's something for everyone at this epic battle. Feel the adrenaline rush as the bands battle it out for the top spot, with expert judges and an enthusiastic audience cheering them on. Experience the magic of live music, and let the beat move you as the bands showcase their unique sound and style. So come and join us for an event of pure entertainment and musical mayhem at the Inter College Battle of Bands! (Day 2: 10:00Am-2:00Pm)",
        rules: [
            "1. Only bands or musical groups composed of current college students may be allowed to compete.",
            "2. Only 1 band from each college is allowed.",
            "3. A minimum of 5 band members are required to be eligible for participation and 1 drummer is compulsory.",
            "4. The event will consist of two rounds:",
            "5. Round 1: Band Performance",
            "6. Round 2: Drummers Face-off",
            "7. Bands must register in advance of the event and may be required to submit a demo recording of their music for consideration. The number of bands that can participate will be limited.",
            "8. The time for the performance of a team will be 10-15 minutes.",
            "9. Bands must bring their own instruments and equipment to the event, although the organizers may provide a basic sound system and a drum set.",
            "10. The competition may be judged by a panel of judges",
            "11. Contestants have to report at least 1 hour before the event timing.",
            "12. Slots are selected on a first come first serve basis.",

            "13. Alcohol/drugs/smoking and such objectionable substances are strictly prohibited within the campus.",
            "14.The decision of the judges will be final.",
            "15. All the participants will receive a participant certificate.",
            "16. A section relevant to the theme should be included in the performance. (Theme=Indian Culture).",
            "17. Extra points will be awarded if you perform two different decades of songs.",
            "18. Rapping is not allowed.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Decibels",
    },
    {
        id: 11,
        name: "Chitrakala",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Chitrakala",
        headingPara: "Step right up and get ready to create a masterpiece like never before! Chitrakala: The Brushless Painting event is a daytime delight that's sure to tickle your creative senses and leave you with a work of art like no other. Experience the thrill of painting without a brush, using innovative and unconventional techniques to create a masterpiece that's uniquely you. From pouring and dripping to splattering and swirling, there's no limit to the possibilities with this exciting and freeform approach. Enjoy the warm sunshine and fresh air as you compete against other daring artists for the title of the best brushless painter. With expert judges and an enthusiastic audience cheering you on, the energy and excitement will be off the charts! So come and join us for a day of experimentation, creativity, and pure fun at the Brushless Painting event. Let your imagination run wild and explore the limitless possibilities of this innovative and unconventional technique. Who knows what masterpiece you'll create? The sky's the limit! (Day 2: 10:00Am-1:00Pm)",
        rules: [
            "1. Participants are required to reach 15 minutes before the start of the competition.",
            "2. Participants will be given painting essentials like colors, paper sheets, and cotton.",
            "3. No brush is allowed.",
            "4. The painting should be an individual effort.",
            "5. Cell phone use will not be allowed.",
            "6. Decisions taken by judges will be final and binding to participants.",
            "7. A limited timeframe will be provided.",
            "8. All the participants will receive a participation certificate.",

        ],

        paymentLink: "",
        redirectLink: "/cultural/Chitrakala",
    },
    {
        id: 12,
        name: "Rangilo",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Rangilo",
        headingPara: "Are you ready to channel your inner artist and create a masterpiece that's both stunning and meaningful? Then get ready for the ultimate Rangoli Making event - a celebration of color, culture, and creativity! Experience the magic of Rangoli, a traditional Indian art form that uses vibrant colors and intricate patterns to create beautiful designs on the ground. From classic motifs to modern interpretations, there's no limit to what you can create with a little bit of imagination and a lot of colorful powders. Join other talented artists as you compete for the title of the best Rangoli maker. With endless possibilities and a rainbow of colors to choose from, there's no better way to spend your day than creating a stunning masterpiece that's both beautiful and meaningful. Get ready to immerse yourself in a world of color, culture, and creativity - the Rangoli way! (Day 1: 1:00Pm-4:00Pm)",
        rules: [
            "1. Rangoli should be 3ft×3ft.",
            "2. There will be only one round of competition.",
            "3. The maximum time to complete the rangoli is 2 hours.",
            "4. Teams will be responsible for the arrangement of material required to prepare Rangoli.",
            "5. Only Rangoli colors can be used for making Rangoli.",
            "6. The participants will not be allowed to refer to any printed material for preparing rangoli.",
            "7. The participants must strictly adhere to the timings.",
            "8. We will provide blank A4-size white sheets of paper to all the participants.",

        ],

        paymentLink: "",
        redirectLink: "/cultural/Rangilo",
    },
    {
        id: 13,
        name: "Rangdet-shirt",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Rang De T-shirt",
        headingPara: "Are you tired of boring and generic T-shirts? Well, get ready to level up your fashion game with our T-Shirt coloring event! It's time to let your imagination run wild and create a shirt that's uniquely you. Our event provides everything you need to design your masterpiece, from top-quality markers to premium tees. So whether you're an aspiring fashion designer or just looking for a fun way to express yourself, come join us for a day of vibrant colors, creative expression, and endless possibilities! (Day 1: 10:00Am-1:00Pm)",
        rules: [
            "1. White t-shirts will be provided by the host college, only one for each participant.",
            "2. Participants may select from any of the given topics for their doodles.",
            "3. Pens, pencils, and fabric colors are to be provided by the host college.",
            "4. Brushes, paper, and carbon paper are allowed",
            "5. If any participant makes a mistake, no extra T-shirt will be provided.",
            "6. Plagiarised submissions will be disqualified.",
            "7. Content needs to be within the bounds of decency.",
            "8. Use of any other materials or ready-made stickers is strictly prohibited.",
            "9. The duration of the competition shall be of 2 hours.",
            "10. Mobile phones or any other electronic devices shall not be allowed during the",
            "competition.",
            "11. Participants shall not be allowed to use any photographs for reference.",
            "12. During the event, some rules might be changed as per the judges.",
            "13. All the participants will receive a participant certificate.",

        ],

        paymentLink: "",
        redirectLink: "/cultural/Rangdet-shirt",
    },
    {
        id: 14,
        name: "Libaaz",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Libaaz",
        headingPara: "Are you ready to immerse yourself in the rich and vibrant culture of India? Then don your favorite traditional attire and join us for our Indian Cosplay event! From colorful sarees to intricately detailed sherwanis, this is your chance to showcase your love for Indian culture and tradition. Whether you're a die-hard fan of Bollywood movies or simply appreciate the beauty of Indian fashion, this event promises to be a feast for the senses. So come prepared to be swept away by the sights, sounds, and tastes of India as we celebrate this amazing culture through the art of cosplay.(Day 2: 10:00Am-1:00Pm)",
        rules: [
            "1. Performance should not exceed more than 5-7 minutes.",
            "Introduction",
            "Act of your character (1 – 2 minutes).",
            "Define your character (Why they are dressed like)",
            "2. The competition is open to all college students.",
            "3. The theme is “Indian culture”.",
            "4. Out of the theme character will be instantly disqualified.",
            "5. The judge's decision will be final and abiding.",
            "6. Each participant will receive a registration number/code after their registration.",
            "7. Participants have to reach 30 minutes prior.",
            "8. All the participants will receive a participation certificate.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Libaaz",
    },
    {
        id: 15,
        name: "Raas",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Raas",
        headingPara: "Get ready to light up your day with our lively Dandiya event! This is the perfect opportunity to immerse yourself in the festive spirit and experience the joy of dance. With colorful sticks in your hands and a smile on your face, you'll join a community of like-minded individuals as we come together to celebrate the rich culture of India. Whether you're an expert in the art of Dandiya or a beginner looking to learn, our event promises to be a day filled with excitement, laughter, and unforgettable memories. So put on your best traditional attire, grab your friends and family, and join us for a fun-filled daytime event that you won't want to miss! (Day 2: 11:00Am-2:00Pm)",
        rules: [
            "1. Anyone can come and join in the dandiya event.",
            "2. No time limit per participant.",
            "3. Sticks will be provided by the event team.",
            "4. There should be no damage to the props, sticks should be returned in proper condition otherwise a penalty would be imposed upon the participant.",
            "5. A penalty will be imposed for vulgar actions, extreme aggression, or doing any act which is inappropriate or harmful.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Raas",
    },
    {
        id: 16,
        name: "Karigari",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Karigari",
        headingPara: "Experience the magic of Indian culture through the lens of creativity and innovation at the DIY Exhibition! This one-of-a-kind event celebrates the vibrant and colorful traditions of India by showcasing the most unique and imaginative DIY creations inspired by Indian culture. From handcrafted textiles and jewelry to repurposed furniture and decor, this exhibition will transport you to a world of Indian artistry and ingenuity. Discover new skills, get inspired, and immerse yourself in the rich tapestry of Indian culture through the lens of DIY. So come and explore this exciting world of self-expression, innovation, and cultural appreciation at the DIY Exhibition based on Indian culture.(Day 1: 10:00Am-3:00Pm)",
        rules: [
            "1. Registration for the event will close 30 minutes prior to the event start time.",
            "2. All college students can participate in the event.",
            "3. No participant is allowed to sell their craft during the exhibition.",
            "4. Planning the layout of the area so that visitors can move freely and view the exhibits.",
            "5. If things are electrically connected so they should be wired accurately and should not cause any harm to visitors.",
            "6. Proper labeling of exhibits with some relevant information must be done.",
            "7. Proper placement of exhibits must be done so that there should be no damage to them.",
            "8. Supervised the exhibits and the supervisor should have the knowledge about the artifacts to answer the questions.",
            "9. Craft projects can be made from a kit of your original design but should be reflective of your skill level",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Karigari",
    },
    {
        id: 17,
        name: "Parchhayi",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Parchhayi",
        headingPara: "Get ready for a thrilling showcase of talent and creativity at the Mono Act Event! This unique daytime event brings together the most skilled and imaginative performers to take the stage and bring to life captivating characters, stories, and emotions through the power of solo acting. With no limitations on genre or style, this event promises to leave you on the edge of your seat as you witness the sheer range and depth of human expression. So come and witness the power of one at the Mono Act Event, where a single performer can captivate and move an entire audience with their artistry and skill.(Day 1: 10:00Am-1:00Pm)",
        rules: [
            "1. The mono act should be related to Indian Culture.",
            "2. The duration of the performance should not exceed 10 minutes. A warning bell will ring after 8 minutes.",
            "3. The participants are supposed to perform according to the theme.",
            "4. Exceeding the time limit, and exceeding the number of participants will lead to a deduction in null points.",
            "5. A team will be disqualified if anyone is found to make use of vulgar or abusive content.",
            "6. The event head should be made aware of the props being used by the performers.",
            "7. The decision of the judges will be final and binding.",
            "8. All the participants will receive a participation certificate.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Parchhayi",
    },
    {
        id: 18,
        name: "Mukabala",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Mukabala",
        headingPara: "Get ready to bring your A-game and showcase your talent like never before at the Face Off event - a daytime extravaganza that's sure to inspire and thrill! Experience the thrill of competition as you go head to head with other talented performers in a battle of dance, singing, and rap. Whether you're a seasoned pro or a fresh face on the scene, there's no better way to showcase your skills and prove that you've got what it takes to come out on top. Enjoy the warm sunshine and fresh air as you compete against other talented performers for the title of the best dancer, singer, or rapper. So come and join us for a day of creativity, fun, and pure talent at the Face Off event. With endless possibilities and a rainbow of skills to choose from, there's no better way to spend your day than competing in a battle of the best. Get ready to bring your best moves, vocals, and rhymes to the stage and let your talent shine! (Day 2: 10:00Am-3:00Pm) ",
        rules: [
            "1. Registration will be on the spot and will close for 1 hour, according to the timings of the particular event.",
            "2. Participants will perform for 2-4 minutes.",
            "3. Two random participants will be selected and they have to perform at the same time on the stage.",
            "4. The winner will be declared on the spot.",
            "5. Any choice of music participants will not be given.",
            "6. All dance forms are allowed including classical.",
            "7. A penalty will be imposed for vulgar actions, extreme aggression, or doing any act which is inappropriate or harmful.",
            "8. Contestants must report 30 minutes prior to event time.",

        ],

        paymentLink: "",
        redirectLink: "/cultural/Mukabala",
    },
    {
        id: 19,
        name: "Mukhote",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Mukhote",
        headingPara: "Get ready to add some color and creativity to your day with the ultimate face painting event - Indian Edition! Experience the magic of Indian culture as you explore the rich tapestry of colors and designs through the art of face painting. From stunning mehndi patterns to intricate peacock feathers, let your imagination run wild and create a masterpiece that's uniquely you. Enjoy the warm and sunny atmosphere of a daytime event as you compete against other talented artists for the title of the best face painter. With expert judges and an enthusiastic crowd, the energy and excitement will be contagious! So come and join us for a fun-filled day of creativity and culture at the Face Painting event - Indian Edition! With endless possibilities and a rainbow of colors to choose from, there's no limit to what you can create. (Day 1: 10:00Am-1:00Pm)",
        rules: [
            " 1. Participants are required to reach 15 minutes before the start of the competition.",
            "2. Participants will be given painting essentials like colors, brushes, and water.",
            "3. Competitors should not use stencils or stamps of any kind.",
            "4. False eyelashes and eye lenses are not allowed.",
            "5. The painting should be an individual effort.",
            "6. Cell phone use will not be allowed.",
            "7. Decisions taken by judges will be final and binding to participants.",
            "8. All the participants will receive a participation certificate.",

        ],

        paymentLink: "",
        redirectLink: "/cultural/Mukhote",
    },
    {
        id: 20,
        name: "Mratika",
        imgSrc: "https://i.ibb.co/51ZNnWz/Genero23-01-1.png",
        heading: "Mratika",
        headingPara: "Are you ready to get your hands dirty and unleash your inner artist? Then join us for the ultimate pottery-making event - a daytime extravaganza that's sure to inspire and delight! Experience the magic of creating something with your own hands as you explore the ancient art of pottery making. From crafting delicate teacups to sculpting intricate figurines, there's no limit to what you can create with a little bit of clay and a lot of imagination. Enjoy the warm sunshine and fresh air as you compete against other talented potters for the title of the best ceramic artist. So come and join us for a day of creativity, fun, and relaxation at the Pottery Making event. With endless possibilities and a rainbow of colors to choose from, there's no better way to spend your day than with your hands in the clay! (Day 1 : 10:00Am-2:00Pm)",
        rules: [
            "1. Participants have to complete the tasks in the given time.",
            "2. Participants can use things like paint, ribbons, glitters, etc. to decorate the pots.",
            "3. No additional clay will be provided.",
            "4. The amount of water will be limited; wasting water can lead to negative markings.",
            "5. All the participants will receive a participation certificate.",
        ],

        paymentLink: "",
        redirectLink: "/cultural/Mratika",
    },
];

export default CulturalData;
